DROP TABLE IF EXIST videos;

 CREATE TABLE videos(
	id_video INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	video VARCHAR(24) NOT NULL,
	views INT UNSIGNED DEFAULT 0
);
INSERT INTO videos(video) VALUES ('auronplay');
